#ifndef ERRORS_H
#define ERRORS_H

#define ERROR_OK 0
#define ERROR_DLN_ADAPTER_OPEN 1
#define ERROR_GET_I2C_PORT_COUNT 2
#define ERROR_NO_I2C_PORTS 3
#define ERROR_DLN_SERVER_CONNECT_FAILED 4
#define ERROR_MASTER_SET_FREQUENCY_FAILED 5
#define WARNING_FREQUENCY_ROUNDED 6
#define ERROR_GET_FREQUENCY_FAILED 7
#define ERROR_MASTER_ENABLE_FAILED 8
#define ERROR_MASTER_DISABLE_FAILED 9
#define ERROR_MASTER_SCAN_FAILED 10
#define ERROR_MASTER_IS_ENABLED_FAILED 11
#define ERROR_SET_REPLY_COUNT_FAILED 12
#define ERROR_GET_REPLY_COUNT 13
#define ERROR_UNVALID_INPUT 14
#define ERROR_READ_FAILED 15
#define ERROR_WRITE_FAILED 16
#define ERROR_INVALID_WRITE_DATA 17
#define ERROR_SEQUENCE_TO_MANY_PATTERNS 18
#define ERROR_COULD_NOT_FIND_SEQUENCE_FILE 19
#define ERROR_COULD_NOT_FIND_ANY_LINES_IN_SEQUENCE_FILE 20
#define ERROR_MISSING_ARGUMENTS 21
#define ERROR_COMMAND_ARGUMENT_MISMATCH 22
#define ERROR_TO_HIGH_IMAGE_NUM 23
#define ERROR_TO_HIGH_LED_AMPLITUDE 24

#define ERROR_SEQUENCE_NUM_ARGS 1000
#define ERROR_SEQUENCE_VALUES 0x10000
//LAST HEX DIGIT IS ARGUMENT NUM, hex digit 3,2,1 is line num

#define LED_TEMP_RETURN_BASE 2000
#define LED_BOARD_TEMP_RETURN_BASE 3000
#define LED_STICKY_RETURN_BASE 4000
#define TI_SEQUENCE_RETURN_BASE 5000
//Sticky bits: (4):OCP (3): Door_open (2): Fan stopped (1): Board_overtemp, (0): LED_overtemp

#endif // ERRORS_H
